//
// Swiftfin is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Jellyfin & Jellyfin Contributors
//

import Foundation

/// Represents a playlist from YouTube Music
struct YTMusicPlaylist: Identifiable, Hashable {

    /// Unique identifier (playlist ID or browse ID)
    let id: String

    /// Playlist title
    let title: String

    /// Playlist description
    let description: String?

    /// Number of tracks in the playlist
    let trackCount: Int?

    /// Available thumbnail images
    let thumbnails: [YTMusicThumbnail]

    /// Author/creator of the playlist
    let author: YTMusicArtistRef?

    /// Privacy status (public, private, unlisted)
    let privacy: Privacy

    /// Total duration as string (e.g., "2 hr 15 min")
    let duration: String?

    /// Year created or last modified
    let year: String?

    /// Whether this is an auto-generated playlist (e.g., artist radio)
    let isAutoGenerated: Bool

    /// Whether this is editable by the current user
    let isEditable: Bool

    // MARK: - Identifiable

    var browseId: String {
        id
    }

    // MARK: - Computed Properties

    /// Best available thumbnail URL
    var thumbnailURL: URL? {
        thumbnails.bestQuality?.url
    }
}

// MARK: - Privacy

extension YTMusicPlaylist {

    enum Privacy: String, Hashable {
        case `public` = "PUBLIC"
        case `private` = "PRIVATE"
        case unlisted = "UNLISTED"
        case unknown

        init(from string: String?) {
            guard let string = string?.uppercased() else {
                self = .unknown
                return
            }

            switch string {
            case "PUBLIC":
                self = .public
            case "PRIVATE":
                self = .private
            case "UNLISTED":
                self = .unlisted
            default:
                self = .unknown
            }
        }
    }
}

// MARK: - Special Playlists

extension YTMusicPlaylist {

    /// Known special playlist types
    enum SpecialPlaylist: String {
        case likedSongs = "LM"
        case history

        var displayName: String {
            switch self {
            case .likedSongs:
                return "Liked Songs"
            case .history:
                return "History"
            }
        }
    }

    /// Check if this is a special system playlist
    var specialType: SpecialPlaylist? {
        if id == "LM" || id.contains("liked") {
            return .likedSongs
        }
        return nil
    }
}
